package aliases

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"

	"github.com/xolan/xoldot/internal/config"
)

var validName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_-]*$`)

const (
	generatedHeader = "# Generated by xoldot. Edit files/aliases.toml instead.\n"
	digestPrefix    = "# xoldot-digest: sha256:"
)

var supportedShells = []string{"bash", "zsh", "fish"}

type Alias struct {
	Name    string `toml:"name"`
	Command string `toml:"command"`
}

type File struct {
	Aliases []Alias `toml:"alias"`
}

type State string

const (
	StateCurrent     State = "current"
	StateMissing     State = "missing"
	StateReplaceable State = "replaceable"
	StateConflict    State = "conflict"
)

type Inspection struct {
	State    State
	Path     string
	Problem  string
	existing []byte
	desired  []byte
}

type Plan struct {
	path       string
	data       []byte
	legacyData []byte
}

func Load(path string) (File, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return File{}, nil
		}
		return File{}, fmt.Errorf("read aliases: %w", err)
	}

	var file File
	if err := toml.NewDecoder(bytes.NewReader(data)).DisallowUnknownFields().Decode(&file); err != nil {
		return File{}, fmt.Errorf("parse %s: %w", path, err)
	}
	if err := Validate(file.Aliases); err != nil {
		return File{}, fmt.Errorf("validate %s: %w", path, err)
	}
	return file, nil
}

func Save(path string, file File) error {
	if err := Validate(file.Aliases); err != nil {
		return err
	}
	file.Aliases = append([]Alias(nil), file.Aliases...)
	sort.Slice(file.Aliases, func(i, j int) bool {
		return file.Aliases[i].Name < file.Aliases[j].Name
	})
	data, err := toml.Marshal(file)
	if err != nil {
		return fmt.Errorf("encode aliases: %w", err)
	}
	return config.WriteFile(path, data, 0o644)
}

func Add(file *File, name, command string) (updated bool, err error) {
	if err := validate(name, command); err != nil {
		return false, err
	}

	for index := range file.Aliases {
		if file.Aliases[index].Name == name {
			file.Aliases[index].Command = command
			return true, nil
		}
	}
	file.Aliases = append(file.Aliases, Alias{Name: name, Command: command})
	return false, nil
}

func isSupportedShell(shell string) bool {
	return slices.Contains(supportedShells, shell)
}

func DetectShell() (string, error) {
	shell := os.Getenv("XOLDOT_SHELL")
	if shell == "" {
		shell = os.Getenv("SHELL")
	}
	shell = filepath.Base(shell)
	switch {
	case isSupportedShell(shell):
		return shell, nil
	case shell == "" || shell == ".":
		return "", fmt.Errorf("cannot detect shell; set SHELL or XOLDOT_SHELL to bash, zsh, or fish")
	default:
		return "", fmt.Errorf("unsupported shell %q; supported shells are bash, zsh, and fish", shell)
	}
}

func Render(path, shell string, aliases []Alias) error {
	plan, err := Prepare(path, shell, aliases)
	if err != nil {
		return err
	}
	return plan.Apply()
}

func Prepare(path, shell string, aliases []Alias) (Plan, error) {
	plan, inspection, err := buildPlan(path, shell, aliases)
	if err != nil {
		return Plan{}, err
	}
	if inspection.State == StateConflict {
		return Plan{}, errors.New(inspection.Problem)
	}
	return plan, nil
}

func Inspect(path, shell string, aliases []Alias) (Inspection, error) {
	_, inspection, err := buildPlan(path, shell, aliases)
	if err != nil {
		return Inspection{}, err
	}
	return inspection, nil
}

func buildPlan(path, shell string, aliases []Alias) (Plan, Inspection, error) {
	if !isSupportedShell(shell) {
		return Plan{}, Inspection{}, fmt.Errorf("unsupported shell %q", shell)
	}

	if err := Validate(aliases); err != nil {
		return Plan{}, Inspection{}, err
	}
	aliases = append([]Alias(nil), aliases...)
	sort.Slice(aliases, func(i, j int) bool {
		return aliases[i].Name < aliases[j].Name
	})

	var body strings.Builder
	for _, alias := range aliases {
		if shell == "fish" {
			fmt.Fprintf(&body, "alias %s '%s'\n", alias.Name, quoteFish(alias.Command))
		} else {
			fmt.Fprintf(&body, "alias %s='%s'\n", alias.Name, quotePOSIX(alias.Command))
		}
	}
	bodyData := []byte(body.String())
	digest := sha256.Sum256(bodyData)
	data := []byte(generatedHeader + digestPrefix + hex.EncodeToString(digest[:]) + "\n" + body.String())
	legacyData := []byte(generatedHeader + body.String())
	inspection, err := inspectOutput(path, data, legacyData)
	if err != nil {
		return Plan{}, Inspection{}, err
	}
	return Plan{path: path, data: data, legacyData: legacyData}, inspection, nil
}

func (plan Plan) Apply() error {
	inspection, err := inspectOutput(plan.path, plan.data, plan.legacyData)
	if err != nil {
		return err
	}
	if inspection.State == StateConflict {
		return errors.New(inspection.Problem)
	}
	if inspection.State == StateCurrent {
		return nil
	}
	return config.WriteFile(plan.path, plan.data, 0o644)
}

func inspectOutput(path string, desired, legacyDesired []byte) (Inspection, error) {
	inspection := Inspection{Path: path}
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		inspection.State = StateMissing
		return inspection, nil
	}
	if err != nil {
		return Inspection{}, fmt.Errorf("inspect alias output %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		inspection.State = StateConflict
		inspection.Problem = fmt.Sprintf("alias output %s exists and is not managed by xoldot", path)
		return inspection, nil
	}
	existing, err := os.ReadFile(path)
	if err != nil {
		return Inspection{}, fmt.Errorf("read alias output %s: %w", path, err)
	}
	if bytes.Equal(existing, desired) {
		inspection.State = StateCurrent
		return inspection, nil
	}
	if bytes.Equal(existing, legacyDesired) {
		inspection.State = StateReplaceable
		inspection.existing = existing
		inspection.desired = desired
		return inspection, nil
	}
	if !bytes.HasPrefix(existing, []byte(generatedHeader+digestPrefix)) {
		inspection.State = StateConflict
		inspection.Problem = fmt.Sprintf("alias output %s exists and is not managed by xoldot", path)
		return inspection, nil
	}
	digestEnd := bytes.IndexByte(existing[len(generatedHeader):], '\n')
	if digestEnd < 0 {
		inspection.State = StateConflict
		inspection.Problem = fmt.Sprintf("alias output %s has local changes", path)
		return inspection, nil
	}
	digestEnd += len(generatedHeader)
	wantDigest := strings.TrimPrefix(string(existing[len(generatedHeader):digestEnd]), digestPrefix)
	body := existing[digestEnd+1:]
	actualDigest := sha256.Sum256(body)
	if wantDigest != hex.EncodeToString(actualDigest[:]) {
		inspection.State = StateConflict
		inspection.Problem = fmt.Sprintf("alias output %s has local changes", path)
		return inspection, nil
	}
	inspection.State = StateReplaceable
	inspection.existing = existing
	inspection.desired = desired
	return inspection, nil
}

func (inspection Inspection) UnifiedDiff() string {
	if inspection.State != StateReplaceable {
		return ""
	}
	var output strings.Builder
	fmt.Fprintf(&output, "--- %s\n", inspection.Path)
	fmt.Fprintf(&output, "+++ %s (planned)\n", inspection.Path)
	fmt.Fprintf(
		&output,
		"@@ -%s +%s @@\n",
		diffRange(inspection.existing),
		diffRange(inspection.desired),
	)
	writeDiffLines(&output, '-', inspection.existing)
	writeDiffLines(&output, '+', inspection.desired)
	return output.String()
}

func diffRange(data []byte) string {
	lines := bytes.Count(data, []byte{'\n'})
	if len(data) > 0 && data[len(data)-1] != '\n' {
		lines++
	}
	if lines == 0 {
		return "0,0"
	}
	return fmt.Sprintf("1,%d", lines)
}

func writeDiffLines(output *strings.Builder, prefix byte, data []byte) {
	for len(data) > 0 {
		lineEnd := bytes.IndexByte(data, '\n')
		if lineEnd < 0 {
			output.WriteByte(prefix)
			output.Write(data)
			output.WriteString("\n\\ No newline at end of file\n")
			return
		}
		output.WriteByte(prefix)
		output.Write(data[:lineEnd+1])
		data = data[lineEnd+1:]
	}
}

func Validate(aliases []Alias) error {
	seen := make(map[string]struct{}, len(aliases))
	for _, alias := range aliases {
		if err := validate(alias.Name, alias.Command); err != nil {
			return fmt.Errorf("invalid alias %q in aliases file: %w", alias.Name, err)
		}
		if _, exists := seen[alias.Name]; exists {
			return fmt.Errorf("alias %q is duplicated", alias.Name)
		}
		seen[alias.Name] = struct{}{}
	}
	return nil
}

func validate(name, command string) error {
	if !validName.MatchString(name) {
		return fmt.Errorf("invalid alias name %q; use letters, numbers, underscores, or hyphens", name)
	}
	if strings.TrimSpace(command) == "" {
		return fmt.Errorf("alias command cannot be empty")
	}
	return nil
}

func quotePOSIX(value string) string {
	return strings.ReplaceAll(value, "'", `'\''`)
}

func quoteFish(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, `'`, `\'`)
}
