package aliases

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"

	"github.com/xolan/xoldot/internal/config"
)

var validName = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_-]*$`)

type Alias struct {
	Name    string `toml:"name"`
	Command string `toml:"command"`
}

type File struct {
	Aliases []Alias `toml:"alias"`
}

func Load(path string) (File, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return File{}, nil
		}
		return File{}, fmt.Errorf("read aliases: %w", err)
	}

	var file File
	if err := toml.Unmarshal(data, &file); err != nil {
		return File{}, fmt.Errorf("parse %s: %w", path, err)
	}
	return file, nil
}

func Save(path string, file File) error {
	sort.Slice(file.Aliases, func(i, j int) bool {
		return file.Aliases[i].Name < file.Aliases[j].Name
	})
	data, err := toml.Marshal(file)
	if err != nil {
		return fmt.Errorf("encode aliases: %w", err)
	}
	return config.WriteFile(path, data, 0o644)
}

func Add(file *File, name, command string) (updated bool, err error) {
	if err := validate(name, command); err != nil {
		return false, err
	}

	for index := range file.Aliases {
		if file.Aliases[index].Name == name {
			file.Aliases[index].Command = command
			return true, nil
		}
	}
	file.Aliases = append(file.Aliases, Alias{Name: name, Command: command})
	return false, nil
}

func DetectShell() (string, error) {
	shell := os.Getenv("XOLDOT_SHELL")
	if shell == "" {
		shell = os.Getenv("SHELL")
	}
	shell = filepath.Base(shell)
	switch shell {
	case "bash", "zsh", "fish":
		return shell, nil
	case "", ".":
		return "", fmt.Errorf("cannot detect shell; set SHELL or XOLDOT_SHELL to bash, zsh, or fish")
	default:
		return "", fmt.Errorf("unsupported shell %q; supported shells are bash, zsh, and fish", shell)
	}
}

func Render(path, shell string, aliases []Alias) error {
	if shell != "bash" && shell != "zsh" && shell != "fish" {
		return fmt.Errorf("unsupported shell %q", shell)
	}

	if err := Validate(aliases); err != nil {
		return err
	}
	sort.Slice(aliases, func(i, j int) bool {
		return aliases[i].Name < aliases[j].Name
	})

	var output strings.Builder
	output.WriteString("# Generated by xoldot. Edit files/aliases.toml instead.\n")
	for _, alias := range aliases {
		if shell == "fish" {
			fmt.Fprintf(&output, "alias %s '%s'\n", alias.Name, quoteFish(alias.Command))
		} else {
			fmt.Fprintf(&output, "alias %s='%s'\n", alias.Name, quotePOSIX(alias.Command))
		}
	}
	return config.WriteFile(path, []byte(output.String()), 0o644)
}

func Validate(aliases []Alias) error {
	for _, alias := range aliases {
		if err := validate(alias.Name, alias.Command); err != nil {
			return fmt.Errorf("invalid alias %q in aliases file: %w", alias.Name, err)
		}
	}
	return nil
}

func validate(name, command string) error {
	if !validName.MatchString(name) {
		return fmt.Errorf("invalid alias name %q; use letters, numbers, underscores, or hyphens", name)
	}
	if strings.TrimSpace(command) == "" {
		return fmt.Errorf("alias command cannot be empty")
	}
	return nil
}

func quotePOSIX(value string) string {
	return strings.ReplaceAll(value, "'", `'\''`)
}

func quoteFish(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	return strings.ReplaceAll(value, `'`, `\'`)
}
